apiVersion: placement.openstack.org/v1beta1
kind: PlacementAPI
metadata:
  name: placement
spec:
  serviceUser: placement
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  databaseUser: placement
  preserveJobs: false
  replicas: 1
  secret: placement-secret
  #resources:
  #  requests:
  #    memory: "500Mi"
  #    cpu: "1.0"
